FileVersion = 1

[Project]
Name = "ImGui"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/x64/Debug/cimgui.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/x64/Release/cimgui.lib"]
